### ISSUE TITLE
Implementation ServerRequestInterface 

### ISSUE THREAD

**Issue by KpuTuK** [guzzle/psr7#43] opened 2015-11-03 20:48 UTC
```php
// Message class implements the Message Interface
class Message implements MessageInterface {
    //put code
}
// Server Request class is an abstract basis for the request
abstract class ServerRequest extends Message implements ServerRequestInterface {
    //put code
}
// Request class inherits and provides the USER (according to PSR) access to all methods
class Request extends ServerRequest implements  RequestInterface {
    // put code
}
```
see https://github.com/KpuTuK/Neiron/tree/master/src/Neiron/Components/Http

**Comment by GrahamCampbell** [comment] 2015-11-03 20:54
?

**Comment by GrahamCampbell** [comment] 2015-11-03 20:54
https://github.com/guzzle/psr7/issues/13

**Comment by KpuTuK** [comment] 2015-11-03 20:59
what? My English is poor.

**Comment by GrahamCampbell** [comment] 2015-11-03 21:49
I'm asking why you opened an issue when we already have one?

**Comment by KpuTuK** [comment] 2015-11-03 23:29
I was not looking pull requests and did not see yours, but the question is still open.

**Comment by mtdowling** [comment] 2015-11-04 23:12
Closing as duplicate of https://github.com/guzzle/psr7/issues/13

**Closed by mtdowling** 2015-11-04 23:12 UTC
