### ISSUE TITLE
Strange behavior of stream_get_meta_data, stream not readable on PHP ^7.1!

### ISSUE THREAD

**Issue by zloyboldin** [guzzle/psr7#174] opened 2017-11-14 11:59 UTC
IDK if it's psr7 problem, but maybe someone can give me advise?
While uploading file stream_get_meta_data return to me "mode" option like this
`["mode"]=> string(3) "rb+"`

But this value is not expected in this array
```
private static $readWriteHash = [
        'read' => [
            'r' => true, 'w+' => true, 'r+' => true, 'x+' => true, 'c+' => true,
            'rb' => true, 'w+b' => true, 'r+b' => true, 'x+b' => true,
            'c+b' => true, 'rt' => true, 'w+t' => true, 'r+t' => true,
            'x+t' => true, 'c+t' => true, 'a+' => true
        ],
```

So i get 'NOT READABLE' exception..
Can you help me with it?

**Comment by zloyboldin** [comment] 2017-11-17 06:46
It seems, that this problem is connected with php 7.1..

**Comment by Tobion** [comment] 2018-04-11 13:13
Closing as duplicate of #183

**Closed by Tobion** 2018-04-11 13:13 UTC
