### ISSUE TITLE
Add __toString to Request

### ISSUE THREAD

**Issue by idontusenumbers** [guzzle/psr7#214] opened 2018-09-06 05:49 UTC
It would be nice if classes like Request had useful toStrings

http://www.php.net/manual/en/language.oop5.magic.php#language.oop5.magic.tostring

**Comment by gmponos** [comment] 2018-09-06 16:30
Duplicate of https://github.com/guzzle/psr7/pull/175

**Comment by idontusenumbers** [comment] 2018-09-06 16:58
After reading through that other ticket, it looks like they have an entirely different goal. My goal was to get better debug information when something like Whoops prints out the value in the stack frame.

**Comment by Tobion** [comment] 2018-11-01 01:40
IMO __toString is not suitable here for debugging as it gives an opinioned result that people might expect something else to deliver like you can see with #175.
For debugging, I can recommend tools like https://symfony.com/doc/current/components/var_dumper.html that do a much better job than __toString can deliver.

**Closed by Tobion** 2018-11-01 01:40 UTC
