### ISSUE TITLE
[BC Break] trimHeaderValues in 1.6 Release

### ISSUE THREAD

**Issue by solverat** [guzzle/psr7#282] opened 2019-07-01 07:40 UTC
With the new release, all headers are getting asserted by its type. Having said that, this introduces a BC break. Symfony's Browserkit Client for example, passes the `https` value as a boolean type:

https://github.com/symfony/symfony/blob/38b9b951a42b908fd7e7e9651e41209bc7e620d1/src/Symfony/Component/BrowserKit/AbstractBrowser.php#L385

After updating guzzlehttp/psr7 to 1.6, this request will fail.

**Comment by Tobion** [comment] 2019-07-01 12:17
Symfony BrowserKit does not use psr7. How does the boolean `https` trigger the error? Do you use `ServerRequest::fromGlobals`? Please provide a reproducer.

**Comment by svandervlugt** [comment] 2019-07-01 15:28
I think I hit the same problem.

In 1.6 ```new GuzzleHttp\Psr7\Response(200, ['Authorization' => null], '')``` throws an InvalidArgumentException while in 1.5.2 it generates the same as 
```new \GuzzleHttp\Psr7\Response(200, ['Authorization' => ''], '')```

**Comment by sagikazarmark** [comment] 2019-07-01 15:57
According to PSR-7 header values must be strings or arrays of strings. 1.6.0 enforces that. While it might be a break from a library point of view, this library is a PSR-7 implementation. Relying on undocumented features is never a good idea.

@Tobion IMHO we should add a warning to the release section saying that this release might break for users not following the PSR-7 specification.

**Comment by Tobion** [comment] 2019-07-01 16:04
Fix in #283

**Comment by sagikazarmark** [comment] 2019-07-01 16:18
IMHO that should only be the solution, if we add back the assertions to 2.x

**Comment by Tobion** [comment] 2019-07-01 20:42
Yes that's a possibility. But let's not do it in 1.6 as it has only been released for 1 day and several people are affected. So more people will follow otherwise.

**Comment by GrahamCampbell** [comment] 2019-07-01 21:18
I disagree it's a BC break. Because the param type was `string[]`, the specification says the behaviour is undefined if you pass something else, and changing the behaviour of something outside of the specification shouldn't be regarded as a BC break.

That said, for reasons of practicality, it doesn't make sense to break the Symfony code when there's a simple way to get the old behaviour back. ;)

**Comment by sagikazarmark** [comment] 2019-07-01 23:16
☝️

**Comment by sagikazarmark** [comment] 2019-07-01 23:26
Fixed in  #283

**Closed by sagikazarmark** 2019-07-01 23:26 UTC
Labels: Awaiting feedback
