### ISSUE TITLE
ServerRequest's parsedBody is empty

### ISSUE THREAD

**Issue by kassner** [guzzle/psr7#414] opened 2021-04-12 19:08 UTC
**PHP version**: 7.4.16

**Description**

From the [PSR-7](https://github.com/php-fig/http-message/blob/efd67d1dc14a7ef4fc4e518e7dee91c271d524e4/src/ServerRequestInterface.php#L152-L167):

> If the request Content-Type is either application/x-www-form-urlencoded
   or multipart/form-data, and the request method is POST, this method MUST
   return the contents of $_POST.

Does it apply to the [ServerRequest](https://github.com/guzzle/psr7/blob/master/src/ServerRequest.php)?

**How to reproduce**
```php
<?php

require 'vendor/autoload.php';

$body = <<<EOF
POST /test HTTP/1.1
Host: localhost
Content-Type: application/x-www-form-urlencoded

id=1&name=test
EOF;

// adapted from GuzzleHttp\Psr7\Message::parseRequest
$data = \GuzzleHttp\Psr7\Message::parseMessage($body);
$matches = [];

if (!preg_match('/^[\S]+\s+([a-zA-Z]+:\/\/|\/).*/', $data['start-line'], $matches)) {
    throw new \InvalidArgumentException('Invalid request string');
}

$parts = explode(' ', $data['start-line'], 3);
$version = isset($parts[2]) ? explode('/', $parts[2])[1] : '1.1';

$request = new \GuzzleHttp\Psr7\ServerRequest(
    $parts[0],
    $matches[1] === '/' ? \GuzzleHttp\Psr7\Message::parseRequestUri($parts[1], $data['headers']) : $parts[1],
    $data['headers'],
    $data['body'],
    $version
);

var_dump($request->getBody()->getContents()); # string(14) "id=1&name=test"
var_dump($request->getParsedBody()); # null
```

**Comment by GrahamCampbell** [comment] 2021-04-12 19:48
Probably because `$data['headers']` is empty?

**Comment by kassner** [comment] 2021-04-12 19:54
Likely no:

```
$data = array(3) {
  'start-line' =>
  string(19) "POST /test HTTP/1.1"
  'headers' =>
  array(2) {
    'Host' =>
    array(1) {
      [0] =>
      string(9) "localhost"
    }
    'Content-Type' =>
    array(1) {
      [0] =>
      string(33) "application/x-www-form-urlencoded"
    }
  }
  'body' =>
  string(14) "id=1&name=test"
}
```

In any case, it doesn't seem to be any code in the ServerRequest class that would parse the body.

**Comment by divineniiquaye** [comment] 2021-04-29 01:17
I don't think there's an issue with the `ServerRequest`, probably it's your code. Debug your code to find the actual problem, and do take your time in resolving the issue.

**Comment by kassner** [comment] 2021-04-29 06:46
@divineniiquaye please refer to the _How to reproduce_. There is only Guzzle code there.

**Comment by GrahamCampbell** [comment] 2021-09-06 08:57
I think this is a feature request, and not a bug? We currently use `$_POST` to determine the parsed body in the fromGlobals, and do not implement it parseMessage.

**Comment by kassner** [comment] 2021-09-06 09:19
It depends on how you want to interpret the PSR-7:

https://github.com/php-fig/http-message/blob/efd67d1dc14a7ef4fc4e518e7dee91c271d524e4/src/ServerRequestInterface.php#L152-L167

**Comment by Nyholm** [comment] 2022-03-13 15:20
Thank you for this issue. 

The ServerRequest is a value object and I see that you are not constructing it correctly. See [ServerRequest::fromGlobals()](https://github.com/guzzle/psr7/blob/master/src/ServerRequest.php#L166-L181) as an example. 

You need to do `withParsedBody()`. 

There is no easy way to fix this and adding method parsing is indeed complex by itself. 

I suggest closing this issue.

**Closed** 2022-03-13 15:43 UTC
