### ISSUE TITLE
Query string and + (plus)

### ISSUE THREAD

**Issue by njohansson** [guzzle/psr7#142] opened 2017-03-22 10:10 UTC
Is it expected behaviour that Uri::withQueryValue() does encode all characters except + sign properly?

```
$request = new \GuzzleHttp\Psr7\Request('GET', 'https://example.org/test.php?key=value');
$currentUri = $request->getUri();

$text = 'Text with a + sign';

$newUri = \GuzzleHttp\Psr7\Uri::withQueryValue($currentUri, 'text', $text);
var_dump((string) $newUri);
```

outputs:
```
string(70) "https://example.org/test.php?key=value&text=Text%20with%20a%20+%20sign"
```
(+ sign is untouched)

If you request this URL towards a PHP endpoint the value of $_GET['text'] will be 'Text with a   sign', i.e. + (as well as %20) are interpreted as spaces which is not my intended behavior.

Or am I expected to URL encode my value before passing to withQueryValue() to clearly state my intention with the + sign?

E.g. either of
```
$newUri = \GuzzleHttp\Psr7\Uri::withQueryValue($currentUri, 'text', urlencode($text));
var_dump((string) $newUri);
$newUri = \GuzzleHttp\Psr7\Uri::withQueryValue($currentUri, 'text', rawurlencode($text));
var_dump((string) $newUri);
```

outputs..
```
string(64) "https://example.org/test.php?key=value&text=Text+with+a+%2B+sign"
string(72) "https://example.org/test.php?key=value&text=Text%20with%20a%20%2B%20sign"
```

..which is what I would expect as any of these requests sent towards e.g. a PHP endpoint would result in that $_GET['text'] is getting the value "Text with a + sign"

**Comment by Tobion** [comment] 2017-03-24 00:19
I see you point. But the problem is `+` is an allowed character in the URI. PSR-7 Uri only encodes characters that would not be allowed literally. But since `+` is an allowed char, it is not encoded. If it was encoded automatically, it would not be possible to create a URI that actually contains a plus on purpose.

So the behavior you describe for `withQueryValue` also applies to `withQuery`. As it's impossible to know which case of a plus the user intends, I don't think it makes sense to encode it automatically as this would completely remove one use-case.

Also you need to keep in mind, that the `+` represenation of a space is only valid in `application/x-www-form-urlencoded` context normally.

Closing as expected behavior. Your solution to explicitly rawurlencode the value beforehand makes sense in this case.

**Closed by Tobion** 2017-03-24 00:19 UTC
