### ISSUE TITLE
eof issue

### ISSUE THREAD

**Issue by sm2017** [guzzle/psr7#184] opened 2018-02-13 15:57 UTC
See https://github.com/aws/aws-sdk-php/issues/1493 , `eof` is not working as expected

```php
while ($data = $steam->read(1024)) {
    echo $data;
    flush();
}
```

Works well but

```php
while (!$stream->eof()) {
    echo $stream->read(1024);
    flush();
}
```

Don't print last chunk

**Comment by sm2017** [comment] 2018-02-21 07:17
@guzzle please reply

**Comment by sagikazarmark** [comment] 2018-02-21 08:34
Some more information would be nice:

- which handler do you use?
- what is the type of the stream object?
- where does this stream object come from?
- what is the type of the underlying resource?
- what happens if you detach the resource from the stream and try to operate on it?

the following code works perfectly for me (with both handlers):

```php
<?php

require_once __DIR__.'/vendor/autoload.php';

$stream =

$client = new GuzzleHttp\Client([
	'handler' => new \GuzzleHttp\Handler\CurlHandler(),
	//'handler' => new \GuzzleHttp\Handler\StreamHandler(),
]);

$response = $client->get(
	'http://httpbin.org/stream/100',
	[
		'debug' => true,
	]
);

echo 'Status code: '.$response->getStatusCode()."\n";
echo 'Body size: '.$response->getBody()->getSize()."\n";

$body = $response->getBody();

while (!$body->eof()) {
	echo $body->read(1024);
	flush();
}
```

**Comment by sm2017** [comment] 2018-02-21 11:48
@sagikazarmark see here for your questions https://github.com/aws/aws-sdk-php/issues/1493

**Comment by sagikazarmark** [comment] 2018-02-21 14:30
@sm2017 it does include the stream object type, but not the rest. You will have to do a little bit more debugging, because we cannot remote debug your software.

We need at least clear and simple instructions to reproduce the issue.

Maybe @kstich can be of help, because right now I can't see how this is a problem with the Stream object itself, rather depends on the way it is used (which could still be a Guzzle bug though, but I can't say for sure).

**Comment by Tobion** [comment] 2018-04-11 13:10
Closing due to missing feedback. I gladly reopen when we can reproduce the problem.

**Closed by Tobion** 2018-04-11 13:10 UTC
