### ISSUE TITLE
InvalidArgumentException: \"___utmvaBIBusFowZ=wDn\u0001qsva; path=/; Max-Age=900\"

### ISSUE THREAD

**Issue by dmtar** [guzzle/psr7#517] opened 2022-06-10 14:07 UTC
**PHP version**: 8.0.19

**Description**
Google analytics header value SOH control character does not pass the correct header value validation
**How to reproduce**
A request with header 

```
'Set-Cookie'=> '___utmvaBIBusFowZ=wDnqsva; path=/; Max-Age=900'
```
Basically what we do is where parent is `GuzzleHttp\Client`

```
$res = parent::request('POST', $url, [
                    'json' => $data,
                    'headers' => $this->headers(),
                ]);
```
where we just set some headers no related to cookies, as well the client config is with `cookies => false`
So the GA cookie is set at some point before we try the above POST request and it's attached in the Client
Probably we can bypass it by creating a Request object ourselves but I'm looking for more elegant and easier solution, if any of course.

**Comment by GrahamCampbell** [comment] 2022-06-10 14:26
Google analytics are violating the HTTP spec here, so this should be reported to them.

**Comment by TimWolla** [comment] 2022-06-13 20:25
Effectively duplicate of #502.

**Comment by GrahamCampbell** [comment] 2022-06-13 20:28
I wonder how the brand new HTTP specs describe cookies?

**Comment by GrahamCampbell** [comment] 2022-06-13 20:30
Oh, they just point at the 2011 spec for the definition of a cookie.

**Closed as completed by GrahamCampbell** 2022-06-13 20:30 UTC

**Comment by TimWolla** [comment] 2022-06-13 20:31
> I wonder how the brand new HTTP specs describe cookies?

The Cookie RFC was not updated and cookies are not part of the core HTTP semantics spec.

In any case [RFC 9110#5.5](https://httpwg.org/specs/rfc9110.html#fields.values) is pretty clear that field values (field is the new name for header) must only consist of `field-vchar`, space and tab. Where `field-vchar = visible ASCII characters + 128-255`, disallowing `0x01`.
